FROM centos:7

########
# base #
########

RUN yum install -y epel-release \
                   deltarpm \
                   which \
                   vim

# cgroup Task Affinity
RUN yum install -y hwloc hwloc-devel

# HDF5 Job Profiling
RUN yum install -y hdf5 hdf5-devel

# HTML Man Pages
RUN yum install -y man2html-core

# IPMI Energy Consumption
RUN yum install -y freeipmi freeipmi-devel

# Lua Support
RUN yum install -y lua lua-devel

# MySQL
RUN yum install -y mariadb mariadb-devel

# PAM Support
RUN yum install -y pam pam-devel

# NUMA Affinity
RUN yum install -y numactl numactl-devel

# Readline Support
RUN yum install -y readline readline-devel

# RRD External Sensor Data Collection
RUN yum install -y rrdtool rrdtool-devel

# smap
RUN yum install -y ncurses ncurses-devel

# sview
RUN yum install -y gtk2 gtk2-devel

#######
# ucx #
#######

RUN yum install -y ucx ucx-devel

############
# libevent #
############

RUN yum install -y libevent libevent-devel

########
# pmix #
########

RUN yum install -y git

RUN yum groupinstall -y "Development Tools"

#########
# munge #
#########

ENV MUNGE_UID_GID=351

# Create group and user munge
RUN groupadd -g ${MUNGE_UID_GID} munge
RUN useradd -c "Runs Uid 'N' Gid Emporium" -d /var/run/munge -g munge -m -s /sbin/nologin -u ${MUNGE_UID_GID} munge

# Install munge
RUN yum install -y munge munge-devel munge-libs

# mkdir -m 700 /etc/munge
# mkdir -m 711 /var/lib/munge
# mkdir -m 700 /var/log/munge
# mkdir -m 755 /var/run/munge
# dd if=/dev/urandom bs=1 count=1024 >/etc/munge/munge.key
# sudo -u munge /usr/sbin/munged

#########
# slurm #
#########

ENV SLURM_VERSION={{ slurm.version }}

RUN yum install -y wget

RUN yum install -y openssl openssl-devel

RUN yum install -y perl-ExtUtils-MakeMaker

RUN yum install -y python3 python3-devel

# Build Slurm rpms
RUN cd /root && \
    wget https://download.schedmd.com/slurm/slurm-${SLURM_VERSION}.tar.bz2 && \
    tar xjf slurm-${SLURM_VERSION}.tar.bz2 && \
    cd slurm-${SLURM_VERSION} && \
    cd .. && \
    tar cjf slurm-${SLURM_VERSION}.tar.bz2 slurm-${SLURM_VERSION} && \
    rpmbuild -ta slurm-${SLURM_VERSION}.tar.bz2

# Install Slurm rpms
RUN yum localinstall -y /root/rpmbuild/RPMS/$(uname -m)/slurm-*${SLURM_VERSION}*

RUN yum install -y supervisor

########
#  GO  #
########
RUN yum install -y golang golang-godoc golang-vet golang-src golang-pkg-linux-amd64


# Entrypoint script
COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["supervisord", "-c", "/etc/supervisord.conf", "--nodaemon"]
